<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Notice Management - Budget Pilot Admin</title>
<link rel="icon" type="image/png" href="<?php echo URLROOT; ?>/public/assets/logos/favicon.png?v=2">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="<?php echo URLROOT; ?>/public/css/common.css"><link rel="stylesheet" href="<?php echo URLROOT; ?>/public/css/admin.css">
<style>
.notice-toolbar{display:flex;justify-content:space-between;align-items:center;gap:16px;margin:20px 0}.notice-btn{border:0;border-radius:8px;background:#101C56;color:#fff;padding:11px 18px;font-weight:600;cursor:pointer}.notice-btn.secondary{background:#fff;color:#374151;border:1px solid #D1D5DB}.notice-btn.danger{background:#fff;color:#B42318;border:1px solid #F1B8B5}.notice-card{background:#fff;border:1px solid #E5E7EB;border-radius:12px;overflow:hidden}.notice-table{width:100%;border-collapse:collapse}.notice-table th,.notice-table td{padding:15px 18px;text-align:left;border-bottom:1px solid #EEF0F3;vertical-align:top}.notice-table th{font-size:.78rem;text-transform:uppercase;letter-spacing:.04em;color:#6B7280;background:#FAFAFB}.notice-title{font-weight:650;color:#111827}.notice-message{font-size:.84rem;color:#6B7280;margin-top:4px;max-width:390px}.pill{display:inline-block;padding:4px 9px;border-radius:999px;font-size:.75rem;font-weight:600}.pill-all{background:#EEF2FF;color:#3730A3}.pill-customer{background:#ECFDF3;color:#027A48}.pill-supplier{background:#FFF7ED;color:#C2410C}.pill-active{background:#ECFDF3;color:#027A48}.pill-inactive{background:#F2F4F7;color:#667085}.row-actions{display:flex;gap:7px}.row-actions button{padding:7px 10px;border-radius:7px;font-weight:600;font-size:.8rem;cursor:pointer}.flash-notice{border-radius:8px;padding:11px 16px;margin:14px 0;font-size:.9rem;font-weight:500;background:#E8F6EE;border:1px solid #BDE6CE;color:#1B6B42}.flash-notice.error{background:#FEF3F2;border-color:#FECDCA;color:#B42318}.modal-backdrop{display:none;position:fixed;inset:0;background:rgba(15,23,42,.5);z-index:999;align-items:center;justify-content:center;padding:20px}.modal-backdrop.open{display:flex}.notice-modal{width:min(620px,100%);background:#fff;border-radius:14px;padding:25px;box-shadow:0 24px 60px rgba(0,0,0,.2)}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.modal-close{border:0;background:transparent;font-size:1.5rem;cursor:pointer}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.form-field.full{grid-column:1/-1}.form-field label{display:block;font-size:.82rem;font-weight:600;color:#374151;margin-bottom:6px}.form-field input,.form-field select,.form-field textarea{width:100%;box-sizing:border-box;border:1px solid #D0D5DD;border-radius:8px;padding:10px 11px;font:inherit}.form-field textarea{min-height:120px;resize:vertical}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.empty-notices{text-align:center;padding:48px;color:#98A2B3}@media(max-width:800px){.notice-card{overflow:auto}.notice-table{min-width:800px}.form-grid{grid-template-columns:1fr}.form-field.full{grid-column:auto}}
</style>
</head>
<body data-page="notices">
<div class="dashboard-layout">
<?php require '../app/Views/admin/_sidebar.php'; ?>
<main class="main-content">
<?php require '../app/Views/admin/_topbar.php'; ?>
<header class="content-header"><div class="header-left"><h2 class="page-title">Notice Management</h2><p class="page-subtitle">Create and manage notices shown to customers and suppliers.</p></div></header>
<?php if(!empty($data['flash'])): ?><div class="flash-notice <?php echo ($data['flash_type']??'')==='error'?'error':''; ?>"><?php echo htmlspecialchars($data['flash']); ?></div><?php endif; ?>
<section class="stat-grid cols-3">
<div class="stat-card"><div class="stat-card-label">Total Notices</div><div class="stat-card-value"><?php echo (int)($data['stats']->total??0); ?></div></div>
<div class="stat-card"><div class="stat-card-label">Active Notices</div><div class="stat-card-value"><?php echo (int)($data['stats']->active??0); ?></div></div>
<div class="stat-card"><div class="stat-card-label">Audience Types</div><div class="stat-card-value">3</div></div>
</section>
<div class="notice-toolbar"><div><h3 style="margin:0">All Notices</h3><p style="margin:4px 0 0;color:#667085;font-size:.88rem">Customers and suppliers only receive notices intended for them.</p></div><button class="notice-btn" id="newNoticeBtn">+ Create Notice</button></div>
<div class="notice-card"><table class="notice-table"><thead><tr><th>Notice</th><th>Audience</th><th>Status</th><th>Expires</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<?php if(empty($data['notices'])): ?><tr><td colspan="6"><div class="empty-notices"><strong>No notices yet.</strong><br>Create your first notice using the button above.</div></td></tr>
<?php else: foreach($data['notices'] as $n): ?>
<tr><td><div class="notice-title"><?php echo htmlspecialchars($n->title); ?></div><div class="notice-message"><?php echo htmlspecialchars(mb_strimwidth($n->message,0,115,'…')); ?></div></td>
<td><span class="pill pill-<?php echo htmlspecialchars($n->audience); ?>"><?php echo ucfirst(htmlspecialchars($n->audience)); ?></span></td>
<td><span class="pill pill-<?php echo htmlspecialchars($n->status); ?>"><?php echo ucfirst(htmlspecialchars($n->status)); ?></span></td>
<td><?php echo $n->expires_at ? date('d M Y',strtotime($n->expires_at)) : 'No expiry'; ?></td><td><?php echo date('d M Y',strtotime($n->created_at)); ?></td>
<td><div class="row-actions"><button type="button" class="notice-btn secondary editNotice" data-id="<?php echo (int)$n->id; ?>" data-title="<?php echo htmlspecialchars($n->title,ENT_QUOTES); ?>" data-message="<?php echo htmlspecialchars($n->message,ENT_QUOTES); ?>" data-audience="<?php echo htmlspecialchars($n->audience); ?>" data-status="<?php echo htmlspecialchars($n->status); ?>" data-expires="<?php echo $n->expires_at?date('Y-m-d\TH:i',strtotime($n->expires_at)):''; ?>">Edit</button>
<form method="POST" action="<?php echo URLROOT; ?>/admin/deleteNotice" onsubmit="return confirm('Delete this notice permanently?');"><input type="hidden" name="notice_id" value="<?php echo (int)$n->id; ?>"><button class="notice-btn danger" type="submit">Delete</button></form></div></td></tr>
<?php endforeach; endif; ?></tbody></table></div>
</main></div>
<div class="modal-backdrop" id="noticeModal"><div class="notice-modal"><div class="modal-head"><div><h3 id="modalTitle" style="margin:0">Create Notice</h3><p style="margin:4px 0 0;color:#667085;font-size:.86rem">Choose who should see this announcement.</p></div><button type="button" class="modal-close" id="closeModal">&times;</button></div>
<form method="POST" id="noticeForm" action="<?php echo URLROOT; ?>/admin/createNotice"><input type="hidden" name="notice_id" id="noticeId">
<div class="form-grid"><div class="form-field full"><label>Notice Title *</label><input name="title" id="noticeTitle" maxlength="150" required placeholder="e.g. Scheduled System Maintenance"></div><div class="form-field full"><label>Message *</label><textarea name="message" id="noticeMessage" required placeholder="Write the notice message..."></textarea></div><div class="form-field"><label>Audience *</label><select name="audience" id="noticeAudience"><option value="all">Everyone</option><option value="customer">Customers only</option><option value="supplier">Suppliers only</option></select></div><div class="form-field"><label>Status *</label><select name="status" id="noticeStatus"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="form-field full"><label>Expiry Date (optional)</label><input type="datetime-local" name="expires_at" id="noticeExpires"></div></div><div class="modal-actions"><button type="button" class="notice-btn secondary" id="cancelModal">Cancel</button><button type="submit" class="notice-btn" id="saveBtn">Create Notice</button></div></form></div></div>
<script src="<?php echo URLROOT; ?>/public/js/admin.js"></script>
<script>
const modal=document.getElementById('noticeModal'),form=document.getElementById('noticeForm');
function closeNoticeModal(){modal.classList.remove('open')}
document.getElementById('newNoticeBtn').onclick=()=>{form.reset();form.action='<?php echo URLROOT; ?>/admin/createNotice';document.getElementById('noticeId').value='';document.getElementById('modalTitle').textContent='Create Notice';document.getElementById('saveBtn').textContent='Create Notice';modal.classList.add('open')};
document.querySelectorAll('.editNotice').forEach(b=>b.onclick=()=>{form.action='<?php echo URLROOT; ?>/admin/updateNotice';document.getElementById('noticeId').value=b.dataset.id;document.getElementById('noticeTitle').value=b.dataset.title;document.getElementById('noticeMessage').value=b.dataset.message;document.getElementById('noticeAudience').value=b.dataset.audience;document.getElementById('noticeStatus').value=b.dataset.status;document.getElementById('noticeExpires').value=b.dataset.expires;document.getElementById('modalTitle').textContent='Edit Notice';document.getElementById('saveBtn').textContent='Save Changes';modal.classList.add('open')});
document.getElementById('closeModal').onclick=closeNoticeModal;document.getElementById('cancelModal').onclick=closeNoticeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeNoticeModal()});
</script></body></html>
